language: php

dist: bionic

notifications:
    email: false

php:
    - "7.1"
    - "7.2"
    - "7.3"
    - "7.4"

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES=" --prefer-lowest"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_install:
    - composer self-update --1
    - phpenv config-rm xdebug.ini

install:
    - composer update $DEFAULT_COMPOSER_FLAGS $DEPENDENCIES

script:
    - composer test:syntax
    - composer test:lint
    - composer test:unit
    - if [ $(php -r "echo PHP_MAJOR_VERSION . PHP_MINOR_VERSION;") == "74" -a "$DEPENDENCIES" == "" ]; then composer test:static; fi;
    - if [ $(php -r "echo PHP_MAJOR_VERSION . PHP_MINOR_VERSION;") == "74" -a "$DEPENDENCIES" == "" ]; then composer test:deptrac; fi;

after_success:
    - sudo chmod +775 schema.sh
    - ./schema.sh
